sudo: required
dist: trusty

stages:
  - test
  - deploy

language: node_js
node_js: 8

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=edge
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download

script:
  - lix run travix interp
  - lix run travix neko
  - lix run travix node
  - lix run travix python
  - lix run travix cpp
  # - lix run travix lua # see: https://github.com/HaxeFoundation/haxe/issues/8068
  # - lix run travix java


# jobs:
#   include:
#     # - stage: test # should uncomment this when there is no matrix above (e.g. only one os, one env, etc)
#     - stage: deploy
#       os: linux
#       install:
#         - npm i -g lix
#         - lix download
#       script: skip
#       env:
#         secure: xxxx
#       after_success:
#         - lix run travix install
#         - lix run travix release