sudo: required
dist: trusty

stages:
  - test
  - deploy

language: node_js
node_js: 8

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=edge
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download

script:
  - lix run travix interp
  - lix run travix neko
  - lix run travix node
  - lix run travix python
  - lix run travix java
