sudo: required
dist: trusty

stages:
  - test
  - deploy

language: node_js
node_js: 8

os:
  - linux
  # - osx

env:
  - secure: "DS5Yw8QDo6C27PePS8/3osv3MpamMS9W3/e/imJjL3NtKves33F0IQgtGU42i/n3XllV26si/G0H4gTI0U6Ekn6xVrg/S2wonGtWvF8xK4DzkwGrAFssWqkD1buvn+lAtOw4W/NPHA6/+dvDQ3fU+rzEIWvQAygFrSOHxFuE+u7pYEX+IYRwpLnsNy0v2T4AxNhQAPEKs6jLX3TukPtihSjYe2HszhRPvVf7QZUvO3zxaOFXROa/XUn3aSExbuw0J7tqekrDPrJWJMgw0Ajobah4UmwCcT1knbdym+nwrf9gw0A59U434m8UA1PG0imL48NxFY6tu1cLkhIxF/gdKsjd3WOZxEA6juAH+55x3Tc0wWTsQ+rNLFsy/NSMS7Om6pXKxqL9PjODEp4eAXyXvff0rOlteTFcGH3F9pEd49d62xhCrNx2opa2fg5J2THbrBBNpeweKp7ooZ79cdNKHXAT79DBOwcPEAFQep79EqPN0dEEqPw+np3La1ob7t8X42d5vc0mStxUklnpNOYbEJ12U5HVv7rACf/cgsdMZe6FC2ao/TUj7QF9irkmzofphKY7RsmETtEjjNm4PMgbemyJ65m2Fy8SFzzEtoTwf64+p09ZyhlLJ3+SXkGcsjDC7KAIzfDktsa6Qid79qU0mmRkXKpfVq1WCbPjX+3H/2o="

  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=edge
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download

script:
  - lix run travix interp
  - lix run travix neko
  - lix run travix node
  - lix run travix python
  - lix run travix cpp
  # - lix run travix lua # see: https://github.com/HaxeFoundation/haxe/issues/8068
  - lix run travix java
  - lix run travix cs


# jobs:
#   include:
#     # - stage: test # should uncomment this when there is no matrix above (e.g. only one os, one env, etc)
#     - stage: deploy
#       os: linux
#       install:
#         - npm i -g lix
#         - lix download
#       script: skip
#       env:
#         secure: xxxx
#       after_success:
#         - lix run travix install
#         - lix run travix release